name: Sync RAG to Hugging Face Space

on:
  push:
    branches: [ main ] # Agar aapki default branch 'master' hai, toh ise 'master' kar dein

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add space https://hammasShani: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@huggingface.co/spaces/hammasShani/hammaspotfolio
          git push --force space main
